In [9]:
import requests
from pprint import pprint
from dataclasses import dataclass, asdict
import json
@dataclass
class Phone:
    ad_id: str
    region_name: str
    price: int
    price_string: str
    can_deposit: bool
    subject_content: str
    body: str
    image_url: str

shop_ids = ['143820887', '139931303', '128013841', '142445059', '132053691', '138953767', '144157887']

def crawl(shop_id, limit=100):
    url = f'https://gateway.chotot.com/v1/public/recommender/ad?ad_id={shop_id}&similar_type=1&limit={limit}'
    data = requests.get(url).json()['data']
    final_res = []
    for d in data:
        try:
            phone_data = asdict(Phone(
                ad_id=d['ad_id'],
                region_name=d['region_name'],
                price=d['price'],
                price_string=d['price_string'],
                can_deposit=d['can_deposit'],
                subject_content=d['subject'],
                body=d['body'],
                image_url=d['image'],
            ))
            final_res.append(phone_data)
        except Exception as e:
            pprint(e)
            continue
    return final_res
data = crawl(shop_ids[0])

import mysql.connector as connector
cnx = connector.connect(user='root', password='psw123', port='6603', host='127.0.0.1', database='local_db')
cursor = cnx.cursor()


for record in data:
    ad_id = record['ad_id']
    shop_id = shop_ids[0]
    region_name = record['region_name']
    price = record['price']
    price_string = record['price_string']
    can_deposit = bool(record['can_deposit'])
    subject_content = record['subject_content']
    body = record['body']
    image_url = record['image_url']
    query = "INSERT INTO phones (ad_id, shop_id, region_name, price, price_string, can_deposit, subject_content, body, image_url) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)"
    values = (ad_id, shop_id, region_name, price, price_string, can_deposit, subject_content, body, image_url)

    cursor.execute(query, values)


cnx.commit()
cursor.close()
cnx.close()

In [2]:
import mysql.connector as connector

cnx = connector.connect(user='root', password='psw123', port='6603', host='127.0.0.1', database='local_db')
cursor = cnx.cursor()

# get all phones
query = "SELECT * FROM phones WHERE subject_content LIKE '%samsung%'"
cursor.execute(query)

result_set = cursor.fetchall()
result_set

[]

In [12]:
import mysql.connector as connector
def init_db():
    host = "127.0.0.1"
    port = '6603'
    database = 'PHONES'

    cnx = connector.connect(user='root', password='psw123', port=port, host=host, database=database)
    cursor = cnx.cursor()
    
    query = \
        '''
        USE PHONES; 
        CREATE TABLE phones (
            ad_id VARCHAR(255) NOT NULL,
            shop_id VARCHAR(255) NOT NULL,
            region_name VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
            price INT NOT NULL,
            price_string VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
            subject_content VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
            can_deposit TINYINT NOT NULL,
            body TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
            image_url VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
            PRIMARY KEY (ad_id)
        );
        CREATE TABLE cud(
            number_of_created INT NOT NULL,
            number_of_updated INT NOT NULL,
            number_of_deleted INT NOT NULL
        );
        

        CREATE TABLE shops(
            shop_id VARCHAR(255) NOT NULL,
            PRIMARY KEY (shop_id)
        );
        insert into cud values (0, 0, 0);

        insert into shops values ('143820887');
        insert into shops values ('139931303');
        insert into shops values ('128013841');
        insert into shops values ('142445059');
        insert into shops values ('132053691');
        insert into shops values ('138953767');
        insert into shops values ('144157887');
        insert into shops values ('144985040');
     '''
    cursor.execute(query, multi=True)
    cursor.close()
    cnx.commit()
    cnx.close()

init_db()

MySQLInterfaceError: Commands out of sync; you can't run this command now

In [29]:
for d in data:
    print(d['ad_id'])
    # if 'condition_ad_name' in d:
    #     print(d['condition_ad_name'])
    # if 'condition_ad' in d:
    #     print(d['condition_ad'])
    print(d['can_deposit'])
    print('-----------------')

141947282
True
-----------------
144816196
True
-----------------
140081443
True
-----------------
144985530
True
-----------------
143822433
True
-----------------
144971107
True
-----------------
144222366
True
-----------------
144742646
True
-----------------
142630849
True
-----------------
143889452
True
-----------------
143805275
True
-----------------
144607170
True
-----------------
144791638
True
-----------------
142285876
True
-----------------
144904128
True
-----------------
142572784
True
-----------------
142307869
True
-----------------
142262888
True
-----------------
139694410
True
-----------------
142104653
True
-----------------
144789170
True
-----------------
143761673
True
-----------------
142860562
True
-----------------
143721499
True
-----------------
142180726
True
-----------------
142055395
True
-----------------
140524613
True
-----------------
140546467
True
-----------------
139538591
True
-----------------
140370582
True
-----------------
144740883
True
-----------------
143456106
True
-----------------
139059050
True
-----------------
144630020
True
-----------------
142155564
True
-----------------
139738435
True
-----------------
140063424
True
-----------------
139567789
True
-----------------
141912802
True
-----------------
143809114
True
-----------------
143429201
True
-----------------
144621828
True
-----------------
142582434
True
-----------------
143637866
True
-----------------
144513068
True
-----------------
144460899
True
-----------------
144332465
True
-----------------
142990920
True
-----------------
144338068
True
-----------------
143479221
True
-----------------
144436970
True
-----------------
141355493
True
-----------------
137146653
True
-----------------
137715243
True
-----------------
137684361
True
-----------------
137054833
True
-----------------
141468323
True
-----------------
141429714
True
-----------------
141410077
True
-----------------
140951414
True
-----------------
144327889
True
-----------------
143418705
True
-----------------
143268843
True
-----------------
144064637
True
-----------------
144144743
True
-----------------
144293155
True
-----------------
143291791
True
-----------------
143214180
True
-----------------
128731672
True
-----------------
143868606
True
-----------------
144100093
True
-----------------
141089703
True
-----------------
143549891
True
-----------------
140300499
True
-----------------
143586217
True
-----------------
143091041
True
-----------------
142855387
True
-----------------
140952003
True
-----------------
143759927
True
-----------------
143219682
True
-----------------
143757109
True
-----------------
141199086
True
-----------------
141198597
True
-----------------
143418998
True
-----------------
143104142
True
-----------------
143595130
True
-----------------
138021085
True
-----------------
143612906
True
-----------------
143721433
True
-----------------
139738022
True
-----------------
143523588
True
-----------------
143468653
True
-----------------
143423400
True
-----------------
143085543
True
-----------------
143191871
True
-----------------
139730704
True
-----------------
143423567
True
-----------------
143100753
True
-----------------
143345732
True
-----------------